
name: rest
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Clean secret management files
      run: |
        rm -f \
          Packages \
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
          name: tessst
          path: /
          if-no-files-found: warn # optional, default is warn
          retention-days: true # optional
    # If true, hidden files will be included in the uploaded artifact. If false, hidden files will be excluded from the uploaded artifact.

          include-hidden-files: false # optional, default is false
          
