name: Delete File

on:
  workflow_dispatch:  # Kích hoạt bằng tay từ giao diện GitHub

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git rm Packages  # Đường dẫn đến tệp bạn muốn xóa
          git commit -m "Delete file"
          git push origin main
