name: Upload File

on:
  push:
    branches:
      - main  # Hoặc bất kỳ nhánh nào bạn muốn

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: aa
          path: Packages
