
name: rest
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: macos-12
    permissions:
      contents: write
    steps:
    - name: Clean secret management files
      run: |
        rm -f \
          Packages \
        echo "n\nDescription: Source Cydia Repo by GitPush <fahlnbg>\n" > Rls;
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}
