name: Delete File

on:
  workflow_dispatch:  # Kích hoạt bằng tay từ giao diện GitHub

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old file
        run: |
          git rm \
          Packages \
          Packages.bz2 \
          Release

      - name: Install Dependencies
        run: chmod +x apt-ftparchive
          
      - name: Creat new file
        run: |
          apt-ftparchive packages ./debs > ./Packages
          bzip2 -c9k ./Packages > ./Packages.bz2

          
          printf "Origin: FAHLNBG Repo\nLabel: fahlnbg\nSuite: stable\nVersion: 1.0\nCodename: ios\nArchitectures: iphoneos-arm iphoneos-arm64\nComponents: main\nDescription: Source  Repo by github-action <fahlnbg>\n" > Rls
	        printf "MD5Sum:\n "$(cat ./Packages | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages --printf="%s")" Packages\n "$(cat ./Packages.bz2 | md5sum | cut -d ' ' -f 1)" "$(stat ./Packages.bz2 --printf="%s")" Packages.bz2\n" > Rls1


         

      - name: Upload
        run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push origin main

          
