name: Complete & Update souce package

on:
  workflow_dispatch:

jobs:
  FAHLNBG-with-love:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Dependencies
        run: |
          if ![ -f "./apt-ftparchive" ]; then
            chmod +x apt-ftparchive
            else echo "Dependencies apt-ftparchive ... PLEASE!!!"
          fi


          
      - name: Delete old file
        run: |
          git rm \
          Packages \
          Packages.bz2
          
      - name: Creat new file Packages , Packages.bz2
        run: |
          apt-ftparchive packages ./debs > ./Packages
          bzip2 -c9k ./Packages > ./Packages.bz2

          
      - name: Creat new file Release
        run: |
          printf "Origin: FAHLNBG Repo\nLabel: FAHLNBG\nSuite: stable\nVersion: 1.0\nCodename: ios\nArchitectures: iphoneos-arm iphoneos-arm64\nComponents: main\nDescription: Source Repo by github-action <fahlnbg>\n" > Release


          # Tính toán checksum và kích thước cho tệp Packages
          echo "MD5Sum:" > Release
          printf "%s\n" "$(md5sum ./Packages | cut -d ' ' -f 1)" "$(stat --format="%s" ./Packages) Package" >> Release
          printf "%s\n" "$(md5sum ./Packages.bz2 | cut -d ' ' -f 1)" "$(stat --format="%s" ./Packages.bz2) Package.bz2" >> Release
               

      - name: Upload
        run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push origin main

          
