name: Delete File

on:
  workflow_dispatch:  # Kích hoạt bằng tay từ giao diện GitHub

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old file
        run: |
          git rm \
          Packages \
          Packages.bz2

      - name: Install Dependencies
        run: chmod +x apt-ftparchive
          
      - name: Creat new file Packages , Packages.bz2
        run: |
          apt-ftparchive packages ./debs > ./Packages
          bzip2 -c9k ./Packages > ./Packages.bz2

          
      - name: Creat new file Release
        run: |
          printf "Origin: FAHLNBG Repo\nLabel: FAHLNBG\nSuite: stable\nVersion: 1.0\nCodename: ios\nArchitectures: iphoneos-arm iphoneos-arm64\nComponents: main\nDescription: Source Repo by github-action <fahlnbg>\n" > Release


          
          # Tính toán checksum và kích thước cho tệp Packages
          echo "MD5Sum:" > Release
          
          if [ -f "./Packages" ]; then
            printf "%s\n" "$(md5sum ./Packages | cut -d ' ' -f 1) %s bytes\n\n" "$(stat --format="%s" ./Packages) Package" >> $REPORT_FILE
          fi

        















         

      - name: Upload
        run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push origin main

          
