name: Delete File

on:
  workflow_dispatch:  # Kích hoạt bằng tay từ giao diện GitHub

jobs:
  build:
    name: 
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete old file
        run: git rm Packages Packages.bz2 Release


      - name: Delete old filejjj
        run: apt-ftparchive packages ./debs > ./Packages

 	- name: sd
  
 	run: bzip2 -c9k ./Packages > ./Packages.bz2



      - name: Upload
      run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push origin main

          
