name: Delete File

on:
  workflow_dispatch:  # Kích hoạt bằng tay từ giao diện GitHub

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old file
        run: |
          git rm \
          Packages \
          Packages.bz2 \
          Release

      - name: Install Dependencies
        run: |
          brew install bzip2 
          chmod +x apt-ftparchive
          
      - name: Delete old filejjj
        run: |
          apt-ftparchive packages ./debs > ./Packages
          bzip2 -c9k ./Packages > ./Packages.bz2

      - name: Upload
        run: |
          git add --all
          git config --global user.name 'FAHLNBG'
          git config --global user.email 'fahlnbg@gmail.com'
          git commit -m "Push Repo"
          git push origin main

          
